### ISSUE TITLE
need to define environmental variable $XATSHOME

### ISSUE THREAD

**Issue by sparverius** [xanadu-lang/xinterp#3]
While testing with a tentative ATS2-0.4.0 release, realized that $XATSHOME needs to be defined in the environment if xats is not already installed elsewhere -- otherwise xats compiler will not find prelude (resulting in reported errors).

To allow people to quickly test it out I suppose we could just export XATSHOME in the build script.

However as discussed, this is somewhat of a usability decision. 
If the design pattern is to clone xanadu into the same directory as the extension, this may quickly become difficult to follow... 

Thoughts?

**Comment by githwxi** [comment]
Yes, we need to adopt a uniform approach to this issue.
I guess that the first thing is to figure out, in this case, how
xinterp is supposed to be used.

**Comment by githwxi** [comment]
Addressed for now by the new build.sh.
